language: node_js
node_js:
  - "node"

cache:
  npm: true # this cashes ~/.npm folder on Travis
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache

script:
  - npm run lint
  - npm run test:unit
  - $(npm bin)/cypress run --record
