language: node_js
node_js:
  - "node"

cache:
  npm: true # this cashes ~/.npm folder on Travis
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache

script:
  - npm run test:unit
  - npm run build:card-data
  - npm run serve & wait-on http://localhost:8080
  - $(npm bin)/cypress run --record --key a8a23feb-51ed-4793-969e-e2caa78d7ccd

deploy:
  provider: pages
  local_dir: dist/
  target_branch: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
